---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: celery-worker
spec:
  template:
    metadata:
      labels:
         app: celery
         tier: async
    spec:
      containers:
      - name: celery-worker
        image: quay.io/kubernetes-for-developers/celery-worker:0.4.0
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
           name: bitnami-rabbitmq-config
        livenessProbe:
          httpGet:
            path: /alive
            port: 5000
          initialDelaySeconds: 1
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /ready
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
      initContainers:
        - name: init-celery-broker
          image: busybox
          command: ['sh', '-c', 'until nslookup message-queue; do echo waiting for message-queue to be available; sleep 2; done;']

